### ISSUE TITLE
PullRequestReleaseNotes -init Requires a token

### ISSUE THREAD

**Issue by darknoon29** [jasminsehic/PullRequestReleaseNotes#26] opened 2019-07-01 13:00 UTC
Hello,

I tried to initialize my config file using the -init to generate the sample yml file but it seems that the provider token is mandatory here to generate the file.

Is it expected ?

![image](https://user-images.githubusercontent.com/13015521/60438393-e3657e00-9c10-11e9-8699-6ffa0a6d708d.png)

**Comment by jasminsehic** [comment] 2019-07-01 13:25
@darknoon29 thanks for your report. I will look into it, it doesn't sound like you should be forced to provide a token to init the config.

**Comment by jasminsehic** [comment] 2019-07-01 15:13
@darknoon29 the issue is resolved in v1.2.3 which will be available shortly.

**Closed as completed by jasminsehic** 2019-07-01 15:13 UTC
